# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('mFrom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='post.User')),
                ('mTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='post.User')),
            ],
        ),
    ]
