# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_course',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
