# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_post_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='default.png', upload_to='img/posts/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(default='default.png', upload_to='img/user/'),
        ),
    ]
