# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170812_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(default='default.jpg', upload_to='img/posts/'),
        ),
    ]
