# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170814_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dateSent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
